# Generated by Django 3.0.8 on 2020-08-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=18)),
                ('release_year', models.IntegerField(max_length=4)),
                ('transmission', models.SmallIntegerField(choices=[(0, 'Manual'), (1, 'Auto'), (2, 'CVT')], default=0)),
            ],
        ),
    ]
